// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1IuaeU1RBUwDsN6Hl6-mu9uAWkBRQH4',
    appId: '1:841877655068:web:67fbd4e20dc618560199d9',
    messagingSenderId: '841877655068',
    projectId: 'es-study-database-5fbdd',
    authDomain: 'es-study-database-5fbdd.firebaseapp.com',
    storageBucket: 'es-study-database-5fbdd.firebasestorage.app',
    measurementId: 'G-C0L3XS03C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCksriyGwtVoO3sSSRIJ-rXRe3jmEITVAg',
    appId: '1:841877655068:android:da3f9d971bfab5c40199d9',
    messagingSenderId: '841877655068',
    projectId: 'es-study-database-5fbdd',
    storageBucket: 'es-study-database-5fbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz9IPvlcTAcj8WJF7mz_ST8vUpR4hAJMA',
    appId: '1:841877655068:ios:f11adbd2e18e074c0199d9',
    messagingSenderId: '841877655068',
    projectId: 'es-study-database-5fbdd',
    storageBucket: 'es-study-database-5fbdd.firebasestorage.app',
    iosBundleId: 'com.example.esstudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz9IPvlcTAcj8WJF7mz_ST8vUpR4hAJMA',
    appId: '1:841877655068:ios:f11adbd2e18e074c0199d9',
    messagingSenderId: '841877655068',
    projectId: 'es-study-database-5fbdd',
    storageBucket: 'es-study-database-5fbdd.firebasestorage.app',
    iosBundleId: 'com.example.esstudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa1IuaeU1RBUwDsN6Hl6-mu9uAWkBRQH4',
    appId: '1:841877655068:web:59eeb9c714c7437f0199d9',
    messagingSenderId: '841877655068',
    projectId: 'es-study-database-5fbdd',
    authDomain: 'es-study-database-5fbdd.firebaseapp.com',
    storageBucket: 'es-study-database-5fbdd.firebasestorage.app',
    measurementId: 'G-TQG55DGWXS',
  );

}