// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANGzSWJPsQk0mSMYlMJ2ZfMn0a7qrDN_I',
    appId: '1:245743168355:web:8e9bba838dbe4e3d3e8156',
    messagingSenderId: '245743168355',
    projectId: 'es-study-99e5b',
    authDomain: 'es-study-99e5b.firebaseapp.com',
    storageBucket: 'es-study-99e5b.firebasestorage.app',
    measurementId: 'G-BKPN8GGTVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaEFnK2K_XU_b-qVS_uDgID0FlCMouhC0',
    appId: '1:245743168355:android:7bc4f1128370fec53e8156',
    messagingSenderId: '245743168355',
    projectId: 'es-study-99e5b',
    storageBucket: 'es-study-99e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoti3lq3tzzDMRmLWh4WcpZq-2rUhw3C8',
    appId: '1:245743168355:ios:5faa69e240a0487b3e8156',
    messagingSenderId: '245743168355',
    projectId: 'es-study-99e5b',
    storageBucket: 'es-study-99e5b.firebasestorage.app',
    iosBundleId: 'com.example.esstudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoti3lq3tzzDMRmLWh4WcpZq-2rUhw3C8',
    appId: '1:245743168355:ios:5faa69e240a0487b3e8156',
    messagingSenderId: '245743168355',
    projectId: 'es-study-99e5b',
    storageBucket: 'es-study-99e5b.firebasestorage.app',
    iosBundleId: 'com.example.esstudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANGzSWJPsQk0mSMYlMJ2ZfMn0a7qrDN_I',
    appId: '1:245743168355:web:b9bfa4762530b6943e8156',
    messagingSenderId: '245743168355',
    projectId: 'es-study-99e5b',
    authDomain: 'es-study-99e5b.firebaseapp.com',
    storageBucket: 'es-study-99e5b.firebasestorage.app',
    measurementId: 'G-FL8G5ZFQG4',
  );
}
